#%RAML 1.0
---
title: QData Control
version: 1
baseUri: http://127.0.0.1:11100/qdata
mediaType: application/json

documentation:
  - title: Started
    content: !include doc/qdata-started.md
  - title: Response
    content: !include doc/qdata-response.md
  - title: Request
    content: !include doc/qdata-request.md
  - title: 全局返回码
    content: !include doc/qdata-code.md


/clusters:
  displayName: 集群
  get:
      description: "查询所有集群信息"
      responses:
            200:
              body:
                application/json:
                  example: |
                      {
                        error_code: 0,
                        message: "",
                        data: [{
                          id: 1,
                          cluster_name: "T 系列",
                          type: "Three-tier",
                          type_name: "三层架构",
                          description: "描述信息",
                          nodes: [node_model],
                          switches: [switch_base_model],
                          create_time: "2017-02-10 10:00:00",
                        }]
                      }
  post:
      description: "添加集群"
      queryParameters:
          nodes:
            type: string
            description: 集群中所有的节点信息
            example: |
                [{
                    "ip": "",
                    "hostname": "qdata-com46-dev",
                    "node_type": "compute",
                    "username": "",
                    "password": "",
                    "ibcard_ip": [],
                    "uuid": "48b843a282ef49aa8042718ac36ca6c7",
                    "port": 22,
                    "ipmi": "10.10.20.146",
                    "pwd_type": 1,
                    "ipmiuser": "",
                    "ipmipwd": ""
                }]
            required: true
          cluster:
            type: string
            description: 集群的基本信息
            example: |
                {
                    "name": "qdata-5.0.0",
                    "description": "test",
                    "type": "Three-tier",
                    "uuid": "48b843a282ef49aa8042718ac36ca6c7",
                    "position": "滨江机房",
                    "room": "1104室",
                    "channel": "A通道",
                    "rack": "F机柜"
                }
            required: true
          switches:
            type: string
            description: 交换机信息
            example: |
                 [{
                    "ip": "10.10.90.241",
                    "guid": "7CFE900300ECF6C0",
                    "port_count": "36"
                 }]
            required: true
      responses:
            200:
              body:
                application/json:
                  example: |
                    {
                        error_code: 0,
                        message: "",
                        data: {
                          id: 1,
                          cluster_name: "T 系列",
                          type: "Three-tier",
                          type_name: "三层架构",
                          description: "描述信息",
                          status: "healthy",
                          location: {
                            position: "滨江机房",
                            room: "1104室",
                            channel: "A通道",
                            rack: "F机架",
                          },
                          monitor: {
                            compute_node: {
                              up: 1,
                              down: 0,
                            },
                            storage_node: {
                              up: 0,
                              down: 1,
                            },
                            ib_switch: {
                              up: 1,
                              down: 1,
                            },
                            ib_switch_data_link: {
                              up: 1,
                              down: 1,
                            },
                          },
                          nodes: [node_model],
                          switches: [switch_base_model],
                          create_time: "2017-02-10 10:00:00",
                          update_time: "2017-02-10 14:00:00",
                        }
                     }

/switches:
  displayName: 交换机
  /find:
    post:
      description: 查询交换机的guid、端口数量
      queryParameters:
          switchs:
            type: string
            description: 交换机ip
            example: |
                ["10.10.90.241"]
            required: true
          nodes:
            type: string
            description: 当前集群下所有节点的信息
            example: |
                [
                    {
                        "ip": "10.10.20.46",
                        "port": 22,
                        "pwd_type": 1,
                        "password": "cljslrl0620",
                        "username": "root"
                    }
                ]
            required: true
      responses:
            200:
              body:
                application/json:
                  example: |
                      {
                        error_code: 0,
                        message: "",
                        data: [{
                            "ip": "",
                            "guid": "",
                            "port_count": ""
                        }]
                      }
