#%RAML 0.8
---
title: QData Control
version: 1
baseUri: "URL前缀: http://127.0.0.1:11100/qdata"
mediaType: application/json

documentation:
  - title: Started
    content: !include doc/qdata-started.md
  - title: Response
    content: !include doc/qdata-response.md
  - title: Request
    content: !include doc/qdata-request.md
  - title: 全局返回码
    content: !include doc/qdata-code.md

traits:
  # 接口响应中不包含 data 字段
  - respWithoutData:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                   "error_code": 0,
                   "data": "",
                   "message": ""
                }
  # 接口响应中包含 data 字段
  - respWithData:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                   "error_code": 0,
                   "data": <<ResponsesData>>,
                   "message": ""
                }
  # 接口响应的描述
  - responseDesc:
      responses:
        200:
          description: <<desc>>
  - paged:
      queryParameters:
        page:
          type: integer
          required: false
        pageSize:
          type: integer
          required: false
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "code": 0,
                  "data": {
                    "page": 1,
                    "pageSize": 100,
                    "totalPage": 1,
                    "totalRow": 2,
                    "list": <<exampleList>>
                  }
                }

/clusters:
  displayName: 集群
  get:
      description: "查询所有集群信息"
      is:
        - responseDesc:
            desc: 返回所有集群的信息
        - respWithData:
            ResponsesData: !include samples/simple_cluster_info_model.sample
  post:
      description: "添加集群"
      queryParameters:
          nodes:
            type: string
            description: 集群中所有的节点信息
            example: !include samples/node_info_model.sample
            required: true
          cluster:
            type: string
            description: 集群的基本信息
            example: !include samples/cluster_info_model.sample
            required: true
          switches:
            type: string
            description: 交换机信息
            example: |
                 [{
                    "ip": "10.10.90.241",
                    "guid": "7CFE900300ECF6C0",
                    "port_count": "36"
                 }]
            required: true
      responses:
            200:
              body:
                application/json:
                  example: !include samples/switches_info_model.sample

/switches:
  displayName: 交换机
  /find:
    post:
      description: 查询交换机的guid、端口数量
      queryParameters:
          switchs:
            type: string
            description: 交换机ip
            example: |
                ["10.10.90.241"]
            required: true
          nodes:
            type: string
            description: 当前集群下所有节点的信息
            example: |
                [
                    {
                        "ip": "10.10.20.46",
                        "port": 22,
                        "pwd_type": 1,
                        "password": "cljslrl0620",
                        "username": "root"
                    }
                ]
            required: true
      responses:
            200:
              body:
                application/json:
                  example: |
                      {
                        error_code: 0,
                        message: "",
                        data: [{
                            "ip": "",
                            "guid": "",
                            "port_count": ""
                        }]
                      }
    delete:
      description: 测试
      responses:
            200:
              body:
                application/json:
                  schema: !include schemas/switches_info_schema.schema
                  example: |
                      example: |
                      {
                        "songId": "550e8400-e29b-41d4-a716-446655440000",
                        "songTitle": "Get Lucky",
                        "albumId": "183100e3-0e2b-4404-a716-66104d440550"
                      }
